import MLayout from '@/layout/MLayout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'sweetalert2/src/sweetalert2.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MLayout>
          {children}
        </MLayout>
        </body>
    </html>
  )
}
